### ISSUE TITLE
Drop custom "wider-than" mixin for Neat's "media" mixin.

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#121]
Neat's [media](http://thoughtbot.github.io/neat-docs/latest/#media) mixin supports: _variables_, _min-width_, _max-width_, etc... basically any [media query](http://www.w3.org/TR/css3-mediaqueries/#media1]) can be passed through. 

By default, `@include media()` uses `min-width` so:

**This would be the normal WDS workflow**

Sass

``` sass
.foo {
    @include media($tablet-landscape) {
         color: $color-black;
    }
}
```

CSS

``` css
@media screen and (min-width: 64rem) {
    .foo {
       color: #000;
    }
}
```

**Plain 'ol pixels**

Sass

``` sass
.foo {
    @include media(768px) {
         color: $color-black;
    }
}
```

CSS

``` css
@media screen and (min-width: 768px) {
    .foo {
       color: #000;
    }
}
```

**Use max-width**

Sass

``` sass
.foo {
    @include media(max-width 768px) {
       color: $color-black;
    }
}
```

CSS

``` css
@media screen and (max-width: 768px) {
    .foo {
       color: #000;
    }
}
```

**Combine both min and max widths using variables**

Sass

``` sass
.foo {
    @include media(min-width $phone-portrait max-width $phone-landscape) {
       color: $color-black;
    }
}
```

CSS

``` css
@media screen and (min-width: 22.5rem) and (max-width: 40rem) {
    .foo {
       color: #000;
    }
}
```

See it in action here: http://neat.bourbon.io/examples/
