### ISSUE TITLE
Fluid Video (object, embed, iframe) CSS

### ISSUE THREAD

**Issue by colorful-tones** [WebDevStudios/wd_s#151]
I thought we had something in place, and maybe got taken out, but thought we should have basic, reusable CSS for this in /base/_media.scss

``` CSS
.fluid-embed {
    height: 0;
    overflow: hidden;
    padding-bottom: 56.25%; // For ratio 16:9. 75% if ratio is 4:3
    position: relative;

    embed,
    object,
    iframe {
        @include position(absolute, 0 null null 0);
        @include size(100%);
    }
}
```

Further reading: 
- CSS-Tricks.com: "[Fluid Width Video](https://css-tricks.com/NetMag/FluidWidthVideo/Article-FluidWidthVideo.php)"
- [EmbedResponsively.com](http://embedresponsively.com/)
