### ISSUE TITLE
Add simple grid using presentational classes

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#167]
I would like to propose, the creation of a simple grid, using presentational classes such as:

`.column-one-third`, `.column-two-thirds`, `.column-one-half`, etc...

Usage would be as follows:

``` scss
// One-half width column.
.column-one-half {
    @include column(6, $gutter, $tablet-portrait);
}
```

(I will explain that mixin in a moment)

I know (back when @stacyk) was still at WDS, we voted against using presentational classes in markup and ripped out a grid. However, after working with this grid on CM (as well as a few personal clients) I find it much easier to build "things". 

**Example:**

Instead of endlessly doing this (our projects are huge and yes, this is tedious and yes, this can get unruly):

``` scss
// The content card.
.content-card  {
    @include fill-parent;

    margin-bottom: $gutter;

    @include media($tablet-portrait) {
       @include span-columns(4)

        margin-bottom: 0;
     }
}
```

I can just write (with Emmet :wink:)...

``` html
<div class="content-section row">
    <div class="content-card column column-one-third">
     </div><!-- .column -->
    <div class="content-card column column-one-third">
     </div><!-- .column -->
    <div class="content-card column column-one-third">
     </div><!-- .column -->
</div><!-- .row -->
```

...and :boom: I have a responsive three column grid. Even better, I haven't forced `.content-card` to be a certain width. Now another developer can use `.content-card` at whatever width they want since the width is being set in the markup.

**Some rules:**
- Grid columns are spelled out verbatim. We'd be following Bootstrap's presentational class structure, without the ambiguous: `.col-xs-4` or `.col-lg-*` presentation. In other words, `row` = a row and `.column-one-third` = 1/3 the total width of the row. 
- Using this grid isn't required. We can still use Neat's `@include span-column(4);` (In fact, the new mixin is powered by Neat.) 
- There are definitely cases where we need to target things directly. We may not have access to the markup. But for setting up page templates and such, I think this grid should be our new "go to" way of scaffolding.

**The new mixin:**

I created `@include column();` to keep things DRY. It's clean and includes all the cruft we have to type over and over (see, it's tedious) and places it into a single mixin with three arguments:

``` scss
// Column mixin
@mixin column( $column-width, $bottom-margin, $breakpoint ) {
    @include fill-parent;

    margin-bottom: $bottom-margin;

    @include media($breakpoint) {
        @include span-columns($column-width);

        margin-bottom: 0;
    }
}
```

(See the mixin here: https://github.com/WebDevStudios/wd_s/blob/grid/assets/sass/utilities/mixins/_columns.scss#L42)

Simply pass in the desired width (just like you would with `@include span-columns()`), the value for the bottom margin, and the breakpoint at which the grid "kicks in". I've taken what we've written for CM and pushed it to this branch:  https://github.com/WebDevStudios/wd_s/commits/grid

**For the naysayers:**
Don't like presentational classes? Well, I hate to break it to everyone but, both _s and wd_s (and a zillion other themes) already use them. Like, everywhere. 

`.site-header`, `.site-footer`, `.main-navigation`, `.page`, etc...

The general consensus is:

> Presentational classes are OKAY...if they do what they say.

I welcome the debate and would love for everyone to checkout the [/grid ](https://github.com/WebDevStudios/wd_s/commits/grid)branch's commits.

**Demo:**
See: https://github.com/WebDevStudios/wd_s/commit/dd1b0e4338528ca029513bb23841d8ccc392034d
![wd_s-proposed-grid-demo](https://cloud.githubusercontent.com/assets/200280/14195540/05b753b8-f780-11e5-9452-98243499fe78.gif)

**Further reading:**
http://tympanus.net/codrops/2013/01/22/defending-presentational-class-names/
http://seesparkbox.com/foundry/naming_css_stuff_is_really_hard
http://sixrevisions.com/css/css-tips/css-tip-2-structural-naming-convention-in-css/
