### ISSUE TITLE
Discussion: Better cross-browser/platform font rendering

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#90]
Having issues with @font-face rendering inconsistently across browsers and operating systems.

[This hero](https://www.apple.com/osx/) looks pixel perfect across all browsers and OSs. Would like to follow Apple's lead, and bring some default CSS to help. 

Thoughts?

``` css
body {
    text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    -moz-font-feature-settings: 'liga', 'kern';
}
```

**Comment by colorful-tones** [comment]
Each of these properties has its own implications, and not necessarily ideal to set on entire body element. 

I think it is good to be aware of their benefits, but use them on case by case basic, and targeting specific elements when necessary. I can't remember how I've come to this conclusion. Will try to dig up some links.

**Comment by gregrickaby** [comment]
I added this to U**r, and the custom font rendered more like the PSD. (Yay!)

HOWEVER - it took longer for the page to render, long enough that I thought I broke everything; which is outlined on [CSS-Tricks](https://css-tricks.com/almanac/properties/t/text-rendering/)

I like this approach:

``` css
p.legibility {
  text-rendering: optimizeLegibility;
}
p.speed {
  text-rendering: optimizeSpeed;
}
```

**Comment by gregrickaby** [comment]
What about adding this to `_normalize.scss`? Moving `text-rendering` to it's own class removed the lag I spoke about in the last message...

``` css
body {
    background: $color-background-body;
    margin: 0; // Remove default margin.
    -webkit-font-smoothing: antialiased; // Control the application of anti-aliasing when fonts are rendered.
    -moz-osx-font-smoothing: grayscale; // Control the application of anti-aliasing when fonts are rendered in OS X.
}

.legibility {
    text-rendering: optimizeLegibility; // Improved kerning pairs & ligatures
    -moz-font-feature-settings: 'liga', 'kern'; // Control over advanced typographic features in OpenType fonts.
}
```

The above code produced this:
![before-after-font-smoothing](https://cloud.githubusercontent.com/assets/200280/10494268/f2580234-727a-11e5-90e3-1b1eab730506.jpg)
